delete from application_workstation_links where 1=1;
delete from user_group_links where 1=1;
delete from job_workstation_links where 1=1;
delete from group_job_links where 1=1;
delete from production_orders where 1=1;
delete from product_history_items where 1=1;
delete from product_histories where 1=1;
delete from qa_reasons where 1=1;
delete from products where 1=1;
delete from virtual_handling_units where 1=1;
delete from jobs where 1=1;
delete from workstations where 1=1;
delete from groups where 1=1;
delete from applications where 1=1;
delete from users where 1=1;

select * from application_workstation_links;
select * from applications;
select * from group_job_links;
select * from groups;
select * from job_workstation_links;
select * from jobs;
select * from product_histories;
select * from product_history_items;
select * from production_orders;
select * from products;
select * from qa_reasons;
select * from user_group_links;
select * from users;
select * from virtual_handling_units;
select * from workstations